# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DispProducts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1083, 801)
        Dialog.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 30, 201, 61))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 121, 20))
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 160, 121, 20))
        self.label_3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 370, 121, 20))
        self.label_4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(550, 370, 111, 31))
        self.label_5.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_5.setObjectName("label_5")
        self.prodid = QtWidgets.QLineEdit(Dialog)
        self.prodid.setGeometry(QtCore.QRect(220, 150, 151, 22))
        self.prodid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.prodid.setObjectName("prodid")
        self.prodname = QtWidgets.QLineEdit(Dialog)
        self.prodname.setGeometry(QtCore.QRect(640, 160, 301, 31))
        self.prodname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.prodname.setObjectName("prodname")
        self.qty = QtWidgets.QLineEdit(Dialog)
        self.qty.setGeometry(QtCore.QRect(260, 370, 121, 22))
        self.qty.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.qty.setObjectName("qty")
        self.price = QtWidgets.QLineEdit(Dialog)
        self.price.setGeometry(QtCore.QRect(700, 370, 113, 22))
        self.price.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.price.setObjectName("price")
        self.FirstButton = QtWidgets.QPushButton(Dialog)
        self.FirstButton.setGeometry(QtCore.QRect(80, 590, 141, 28))
        self.FirstButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.FirstButton.setObjectName("FirstButton")
        self.PreviousButton = QtWidgets.QPushButton(Dialog)
        self.PreviousButton.setGeometry(QtCore.QRect(300, 590, 131, 28))
        self.PreviousButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.PreviousButton.setObjectName("PreviousButton")
        self.NextButton = QtWidgets.QPushButton(Dialog)
        self.NextButton.setGeometry(QtCore.QRect(510, 590, 141, 31))
        self.NextButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.NextButton.setObjectName("NextButton")
        self.LastButton = QtWidgets.QPushButton(Dialog)
        self.LastButton.setGeometry(QtCore.QRect(780, 590, 131, 28))
        self.LastButton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.LastButton.setObjectName("LastButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">List of Products</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Product ID</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Product Name</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Quantity</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Price</span></p></body></html>"))
        self.FirstButton.setText(_translate("Dialog", "First"))
        self.PreviousButton.setText(_translate("Dialog", "Previous"))
        self.NextButton.setText(_translate("Dialog", "Next"))
        self.LastButton.setText(_translate("Dialog", "Last"))
